language: scala
env:
  global:
  - IMAGE_NAME=ilyavasin/gallery
  - secure: l6WrWwo7u5OMXK+h8lHVt9eMkR871tZsuulWRLljhwJrFkeMaXiV8jsLuVV/QwSY0DvlezK2LdQUppig0Moc2yg1eQradP+j9v2d26rpi9wyEbeNvirOqF2djB92fXisLi40Dq2A4vddnx/peoweo8YjIa2QfbK0sVeaoipXOaNH3daP7lrSyXWkePaDo7WaNVlWGwfBLa2xVyOipavBCtjZ1bb4HpOhMpsPxUglfajVLaEyumpvBhhvSEPMXyvfCII83/hA6/55cZwqfemE1c50KPxf+4GWVuheB1b9NPB16L/avcGXocPiwNkIXP/RPHqc8Kx/yJgJcDJ1botuU5feueR7vElY/dyLVqy8/A2TXPQonojwUHjUGXTsgb/Yvhqab2cSv7hl5prKuJKtHD4BVJcuovg5iIYI/Pe0cKodT17WiowYlVIbD8HigLktTUlAdegWboBESMx7IQFRhHKEnlzU5jvN05jMz6cvQ7wX2K22DSHY37ue0OMqZx9ak256ahwWSsiaHn/XkBTOusg0sRLH5NvLmaEn0Nt6hPzniKzw1ASQTaYBImYelHQ87lSwGD6flcrxkx4T96BTJxNSUCQ7SvKcISXCngAh+74wy7e/3dtteRdiMUCqUKEf6PGvNoBMrQDdXXT7wKdd1QkmhzDlKVs/ZDmOGfZPF+A=
  - secure: k9K+Mo/pwelqswok0dGTOCDWpdBMtRLSF12YjHwIlt1ZVuMo7Fyb6mGze2ziqmbJk+ulOIuag6rfASP8oBMKeuH+FSnoUfowkSHYMCgGEUl41E7R6rfWuEVDyBchqg+0qZ1E9HDFbiaPay+vVBdbuGCSW9sT+rlFNoeIG/JQZPyvooVd/Ph6cDPF8dpBLZQ8TJkQRD2Y29TXR3EKk/nWAroNkF0G9UAemUj+X3CSZvOA6QwOFO6QVBISZiev8vEf5pX5kh5ShCpaDCgUaa7LBydVYlc2m4AWsb1JPfRyIMxAaSycgs/KpIMX+27WJjPPE4OryvQ975BPsTPNfoAfYHOCHG5B8KsiVt3HtMjd7Sz477g7iLq7S7/dKjbqO0U1ned5lIWrYoe5vmFWlDQ0tuSpCH7QovbRYMwjT1WSB2mlX458ltXBJeU4gD7nA0NpIjHZwe9tkHaSzWK5xSKza1jwkvfY9GQyC7kJ9bxWTkrFvDqDmAJ4m3LNKQLnZs/ILsmJKRYH0B/oVVP8mvqMnxZ/RBeq632qXrn4B9F6owuNBrRv5ceuDVVGiRii4go55geTptK4tCFE7+RkAXjxmElWd4giHuk4fkqbMpa9VzHA/v7VF+M2YWAmTS9n1zm9S3gAEQrmTqymRLbxTLIUduQcyi32zlr5FHo++5WOaLY=
scala:
   - 2.12.8
services:
   - docker
before_script:
   - mkdir backend/src/main/resources/frontend
   - cd frontend
   - npm install
   - npm run-script build
   - cp -r dist/* ../backend/src/main/resources/frontend/
   - cd ../
script:
   - sbt ++$TRAVIS_SCALA_VERSION backend/compile
   - sbt ++$TRAVIS_SCALA_VERSION backend/assembly
   - docker build --tag $IMAGE_NAME .
before_deploy:
   - echo $DOCKERHUB_PASSWD | docker login -u $DOCKERHUB_LOGIN --password-stdin
   - docker tag $IMAGE_NAME ${IMAGE_NAME}:latest
deploy:
  provider: script
  script: docker push ${IMAGE_NAME}:latest
  on:
    branch: master
