language: scala
scala:
   - 2.12.8
services:
  - docker

before_script:
   - mkdir backend/src/main/resources/frontend
   - cd frontend
   - npm install
   - npm run-script build
   - cp -r dist/* ../backend/src/main/resources/frontend/
   - cd ../

script:
  - sbt ++$TRAVIS_SCALA_VERSION backend/compile
  - sbt ++$TRAVIS_SCALA_VERSION backend/assembly
  - docker build .

